export const dummyitems = [
  {
    id: 1,
    name: 'Yogurt',
    date: '2022-12-31',
    quantity: '2',
    storage: 'Fridge',
    warningActive: false,
  },
  {
    id: 2,
    name: 'Milk',
    date: '2022-12-31',
    quantity: '1',
    storage: 'Fridge',
    warningActive: true,
  },
  {
    id: 3,
    name: 'Cheese',
    date: '2034-03-12',
    quantity: '1',
    storage: 'Fridge',
    warningActive: true,
  },
  {
    id: 4,
    name: 'Eggs',
    date: '2034-03-12',
    quantity: '6',
    storage: 'Fridge',
    warningActive: false,
  },
  {
    id: 5,
    name: 'Butter',
    date: '2034-03-12',
    quantity: '1',
    storage: 'Fridge',
    warningActive: false,
  },
  {
    id: 6,
    name: 'Pizza',
    date: '2034-03-12',
    quantity: '3',
    storage: 'Freezer',
    warningActive: false,
  },
  {
    id: 7,
    name: 'mixed veggies',
    date: '2034-03-12',
    quantity: '5',
    storage: 'Freezer',
    warningActive: false,
  },
  {
    id: 8,
    name: 'Ice Cream',
    date: '2034-03-12',
    quantity: '2',
    storage: 'Freezer',
    warningActive: false,
  },
  {
    id: 9,
    name: 'Rice',
    date: '2034-03-12',
    quantity: '2',
    storage: 'Pantry',
    warningActive: false,
  },
  {
    id: 10,
    name: 'Spaghetti',
    date: '2034-03-12',
    quantity: '1',
    storage: 'Pantry',
    warningActive: false,
  },
];
